//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedLibrary.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a     &lt;p&gt;A system where different groups of friends can make predictions about football tournaments. In Colombia, it’s called “Polla”; in Argentina, “Prode”; and in the United States, “Fantasy.” The idea is that any number of football tournaments, such as the Copa América, the World Cup, the Euro Cup, the Champions League, or the Colombian League, among others, can be registered. Groups of friends will be able to form their own “Pollas” and make predictions about the matches. Once the matches are completed an [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Match to Tournament.
        /// </summary>
        public static string AddMatchToTournament {
            get {
                return ResourceManager.GetString("AddMatchToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Team.
        /// </summary>
        public static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Team to Tournament.
        /// </summary>
        public static string AddTeamToTournament {
            get {
                return ResourceManager.GetString("AddTeamToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator Registration.
        /// </summary>
        public static string AdminRegister {
            get {
                return ResourceManager.GetString("AdminRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin users group.
        /// </summary>
        public static string AdminUsersGroup {
            get {
                return ResourceManager.GetString("AdminUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authorizing....
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Match.
        /// </summary>
        public static string CloseMatch {
            get {
                return ResourceManager.GetString("CloseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to close the match {0} Vs. {1}?.
        /// </summary>
        public static string CloseMatchConfirmMessage {
            get {
                return ResourceManager.GetString("CloseMatchConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Match.
        /// </summary>
        public static string CloseMatchTitle {
            get {
                return ResourceManager.GetString("CloseMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Common Use.
        /// </summary>
        public static string CommonUse {
            get {
                return ResourceManager.GetString("CommonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for confirming your email, you can now log in to the system..
        /// </summary>
        public static string ConfirmedEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email confirmation.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press the button to confirm your account..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To join the group: {0}, click the button..
        /// </summary>
        public static string ConfirmGroupMessage {
            get {
                return ResourceManager.GetString("ConfirmGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy invitation.
        /// </summary>
        public static string CopyInvitationURLTitle {
            get {
                return ResourceManager.GetString("CopyInvitationURLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CreatedAt.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete the {0}: {1}?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departament.
        /// </summary>
        public static string Departament {
            get {
                return ResourceManager.GetString("Departament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double Points.
        /// </summary>
        public static string DoublePoints {
            get {
                return ResourceManager.GetString("DoublePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double Points Match.
        /// </summary>
        public static string DoublePointsMatchMessage {
            get {
                return ResourceManager.GetString("DoublePointsMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit User Profile.
        /// </summary>
        public static string EditUserProfile {
            get {
                return ResourceManager.GetString("EditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email you entered already exists..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record not found..
        /// </summary>
        public static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot be deleted because it has related records..
        /// </summary>
        public static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record you are trying to create already exists..
        /// </summary>
        public static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The country Id is not valid..
        /// </summary>
        public static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The team Id is not valid..
        /// </summary>
        public static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect email or password..
        /// </summary>
        public static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the maximum number of attempts, your account is blocked, please try again in 5 minutes..
        /// </summary>
        public static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has not been enabled, you must follow the instructions in the email sent to enable the user..
        /// </summary>
        public static string ERR008 {
            get {
                return ResourceManager.GetString("ERR008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tournament Id is not valid..
        /// </summary>
        public static string ERR009 {
            get {
                return ResourceManager.GetString("ERR009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The local Id is not valid..
        /// </summary>
        public static string ERR010 {
            get {
                return ResourceManager.GetString("ERR010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The visitor Id is not valid..
        /// </summary>
        public static string ERR011 {
            get {
                return ResourceManager.GetString("ERR011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match Id is not valid..
        /// </summary>
        public static string ERR012 {
            get {
                return ResourceManager.GetString("ERR012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user Id is not valid..
        /// </summary>
        public static string ERR013 {
            get {
                return ResourceManager.GetString("ERR013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The group Id is not valid..
        /// </summary>
        public static string ERR014 {
            get {
                return ResourceManager.GetString("ERR014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user group is not valid..
        /// </summary>
        public static string ERR015 {
            get {
                return ResourceManager.GetString("ERR015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The prediction Id is not valid..
        /// </summary>
        public static string ERR016 {
            get {
                return ResourceManager.GetString("ERR016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The group code is not valid..
        /// </summary>
        public static string ERR017 {
            get {
                return ResourceManager.GetString("ERR017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This match is no longer open to predictions..
        /// </summary>
        public static string ERR018 {
            get {
                return ResourceManager.GetString("ERR018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you forgotten your password?.
        /// </summary>
        public static string ForgottenYourPassword {
            get {
                return ResourceManager.GetString("ForgottenYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goals Local.
        /// </summary>
        public static string GoalsLocal {
            get {
                return ResourceManager.GetString("GoalsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a value greater than or equal to zero in local goals..
        /// </summary>
        public static string GoalsLocalError {
            get {
                return ResourceManager.GetString("GoalsLocalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goals Visitor.
        /// </summary>
        public static string GoalsVisitor {
            get {
                return ResourceManager.GetString("GoalsVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a value greater than or equal to zero in visitor goals..
        /// </summary>
        public static string GoalsVisitorError {
            get {
                return ResourceManager.GetString("GoalsVisitorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group: {0} has been created, with code: {1}, Invitation URL {2} has been copied to clipboard, please share it with your friends to join your group..
        /// </summary>
        public static string GroupCreated {
            get {
                return ResourceManager.GetString("GroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group Details.
        /// </summary>
        public static string GroupDetails {
            get {
                return ResourceManager.GetString("GroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HireDate.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image is rectangular.
        /// </summary>
        public static string ImageIsRectangular {
            get {
                return ResourceManager.GetString("ImageIsRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image is square.
        /// </summary>
        public static string ImageIsSquare {
            get {
                return ResourceManager.GetString("ImageIsSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group invitation link {0} copied to clipboard. Share it with your friends to join the group..
        /// </summary>
        public static string InvitationURLCopied {
            get {
                return ResourceManager.GetString("InvitationURLCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Image Square?.
        /// </summary>
        public static string IsImageSquare {
            get {
                return ResourceManager.GetString("IsImageSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join an existing group.
        /// </summary>
        public static string JoinExistingGroup {
            get {
                return ResourceManager.GetString("JoinExistingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Group.
        /// </summary>
        public static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LastUser.
        /// </summary>
        public static string LastUser {
            get {
                return ResourceManager.GetString("LastUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to leave the page and lose your changes?.
        /// </summary>
        public static string LeaveAndLoseChanges {
            get {
                return ResourceManager.GetString("LeaveAndLoseChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must be between {2} and {1} characters..
        /// </summary>
        public static string LengthField {
            get {
                return ResourceManager.GetString("LengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to log out?.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you log out, you will need to log back in to access your account..
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail forwarding.
        /// </summary>
        public static string MailForwarding {
            get {
                return ResourceManager.GetString("MailForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Active.
        /// </summary>
        public static string MatchActive {
            get {
                return ResourceManager.GetString("MatchActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Inactive.
        /// </summary>
        public static string MatchInactive {
            get {
                return ResourceManager.GetString("MatchInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} cannot be longer than {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field must have at least {1} characters..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a local team..
        /// </summary>
        public static string MustSelectLocalTeam {
            get {
                return ResourceManager.GetString("MustSelectLocalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a visitor team..
        /// </summary>
        public static string MustSelectVisitorTeam {
            get {
                return ResourceManager.GetString("MustSelectVisitorTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Groups.
        /// </summary>
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not part of any group. You can join a group using the URL or code shared by the group administrator, or you can view the available groups on the homepage and then ask the administrator to activate you so you can enter your predictions. You can also create your own group of friends..
        /// </summary>
        public static string NoGroups {
            get {
                return ResourceManager.GetString("NoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No records to show....
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not authorized to view this content....
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there is nothing on this route..
        /// </summary>
        public static string NothingInRoute {
            get {
                return ResourceManager.GetString("NothingInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not a user yet? Register here.
        /// </summary>
        public static string NotUserYet {
            get {
                return ResourceManager.GetString("NotUserYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of employees.
        /// </summary>
        public static string NumberEmployees {
            get {
                return ResourceManager.GetString("NumberEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password and confirmation are not the same..
        /// </summary>
        public static string PasswordAndConfirmationDifferent {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Changed Successfully..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully, you can now log in with your new password..
        /// </summary>
        public static string PasswordRecoveredMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PredictedScore.
        /// </summary>
        public static string PredictedScore {
            get {
                return ResourceManager.GetString("PredictedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prediction.
        /// </summary>
        public static string Prediction {
            get {
                return ResourceManager.GetString("Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predictions Balance.
        /// </summary>
        public static string PredictionsBalance {
            get {
                return ResourceManager.GetString("PredictionsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real Score.
        /// </summary>
        public static string RealScore {
            get {
                return ResourceManager.GetString("RealScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record created successfully..
        /// </summary>
        public static string RecordCreatedOk {
            get {
                return ResourceManager.GetString("RecordCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted successfully..
        /// </summary>
        public static string RecordDeletedOk {
            get {
                return ResourceManager.GetString("RecordDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record saved successfully..
        /// </summary>
        public static string RecordSavedOk {
            get {
                return ResourceManager.GetString("RecordSavedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Records Number:.
        /// </summary>
        public static string RecordsNumber {
            get {
                return ResourceManager.GetString("RecordsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email has been sent to you with instructions on how to recover your password..
        /// </summary>
        public static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectangular.
        /// </summary>
        public static string Rectangular {
            get {
                return ResourceManager.GetString("Rectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register as new user.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request Types.
        /// </summary>
        public static string RequestTypes {
            get {
                return ResourceManager.GetString("RequestTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend account activation email.
        /// </summary>
        public static string ResendAccountActivationEmail {
            get {
                return ResourceManager.GetString("ResendAccountActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a Country --.
        /// </summary>
        public static string SelectACountry {
            get {
                return ResourceManager.GetString("SelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a Team --.
        /// </summary>
        public static string SelectATeam {
            get {
                return ResourceManager.GetString("SelectATeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a Tournament --.
        /// </summary>
        public static string SelectATournament {
            get {
                return ResourceManager.GetString("SelectATournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Date....
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a File….
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Time....
        /// </summary>
        public static string SelectTime {
            get {
                return ResourceManager.GetString("SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been created successfully. An email has been sent to you with instructions on how to activate your account..
        /// </summary>
        public static string SendEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("SendEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Single Points Match.
        /// </summary>
        public static string SinglePointsMatchMessage {
            get {
                return ResourceManager.GetString("SinglePointsMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soccer predictions app.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tournament.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tournament is active.
        /// </summary>
        public static string TournamentActive {
            get {
                return ResourceManager.GetString("TournamentActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tournament is inactive.
        /// </summary>
        public static string TournamentInactive {
            get {
                return ResourceManager.GetString("TournamentInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tournaments.
        /// </summary>
        public static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correspondence Type.
        /// </summary>
        public static string TypeCorrespondence {
            get {
                return ResourceManager.GetString("TypeCorrespondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of Document.
        /// </summary>
        public static string TypeDocument {
            get {
                return ResourceManager.GetString("TypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UpdatedAt.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User added to the group. The user can now enter and enter their predictions..
        /// </summary>
        public static string UserAddedToGroupOk {
            get {
                return ResourceManager.GetString("UserAddedToGroupOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registration.
        /// </summary>
        public static string UserRegister {
            get {
                return ResourceManager.GetString("UserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid email..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User ID is required.
        /// </summary>
        public static string ValidUserId {
            get {
                return ResourceManager.GetString("ValidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitor.
        /// </summary>
        public static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watch.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watch Predictions.
        /// </summary>
        public static string WatchPredictions {
            get {
                return ResourceManager.GetString("WatchPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
